// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31loXS7-uVVOOmS9xcXWqVey0P2bU6tM',
    appId: '1:531472729495:web:80b3896ad74232a5de30d2',
    messagingSenderId: '531472729495',
    projectId: 'cicerone-e0f45',
    authDomain: 'cicerone-e0f45.firebaseapp.com',
    storageBucket: 'cicerone-e0f45.appspot.com',
    measurementId: 'G-H8GXSXVF8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQOmuhEt3A0JeMhc_tmsY93b1pvmiJlY',
    appId: '1:531472729495:android:c95f97db3eac08dfde30d2',
    messagingSenderId: '531472729495',
    projectId: 'cicerone-e0f45',
    storageBucket: 'cicerone-e0f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdKcEunariHnVqHzRFKcga3-PiHR45w0',
    appId: '1:531472729495:ios:ef7f5584b671adcede30d2',
    messagingSenderId: '531472729495',
    projectId: 'cicerone-e0f45',
    storageBucket: 'cicerone-e0f45.appspot.com',
    iosClientId: '531472729495-0eeb4t5ej22dtf817jpiibtd713o8atv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cicerone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhdKcEunariHnVqHzRFKcga3-PiHR45w0',
    appId: '1:531472729495:ios:ef7f5584b671adcede30d2',
    messagingSenderId: '531472729495',
    projectId: 'cicerone-e0f45',
    storageBucket: 'cicerone-e0f45.appspot.com',
    iosClientId: '531472729495-0eeb4t5ej22dtf817jpiibtd713o8atv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cicerone',
  );
}
